server:
  port: 8081
spring:
  application:
    name: spring-boot-study
  datasource:
    druid:
      name: druid-dev
      url: jdbc:mysql://127.0.0.1/study?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  redis:
    host: 127.0.0.1
    password:
    database: 0
    port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    useGeneratedKeys: true
    cache-enabled: false
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.spring.study.entity
  typeHandlersPackage: com.spring.study.typeHandler

data-cache:
  config:
    video-tag-list:
      expireAfterWrite: 30
      maximumSize: 100

ignored:
  urls:
    - /user/register
    - /login
    - /v2/api-docs
    - /swagger-resources
    - /swagger-resources/**
    - /configuration/ui
    - /configuration/security
    - /swagger-ui.html
    - /webjars/**
    - /druid1/**